### ISSUE TITLE
 It's current state is: startFailed

### ISSUE THREAD

**Issue by nick-youngblut** [nextflow-io/vscode-language-nextflow#52]
None of the Nextflow extension features are working.

I'm getting the following Runtime Status:

<img width="709" alt="Screenshot 2024-11-11 at 11 48 48 AM" src="https://github.com/user-attachments/assets/4617724a-520f-452c-b440-69e049238feb">

Re-installing the extension does not help. 

I'm using `v1.0.0` of the extension on a MacOS `Sonoma 14.7 (23H124)`

```bash
java --version
openjdk 11.0.25 2024-10-15
OpenJDK Runtime Environment Homebrew (build 11.0.25+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.25+0, mixed mode)
```

**Comment by ameintjes** [comment]
The minimum Java version is now ["Java 17 (or later, up to 23)"](https://www.nextflow.io/docs/latest/install.html#requirements)

**Comment by nvnieuwk** [comment]
I also have this issue when trying to load the extension on a remote session:

<details>

<summary>Stacktrace</summary>

```
2024-11-12 12:15:06.021 [info] Extension host with pid 2647756 started
2024-11-12 12:15:06.021 [error] Error: EEXIST: file already exists, open '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68/vscode.lock'
2024-11-12 12:15:06.023 [info] Lock '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68/vscode.lock': Could not acquire lock, checking if the file is stale.
2024-11-12 12:15:06.025 [info] Lock '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68/vscode.lock': The lock does not look stale, elapsed: 714 ms, giving up.
2024-11-12 12:15:06.029 [error] Error: EEXIST: file already exists, open '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68-1/vscode.lock'
2024-11-12 12:15:06.029 [info] Lock '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68-1/vscode.lock': Could not acquire lock, checking if the file is stale.
2024-11-12 12:15:06.029 [info] Lock '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68-1/vscode.lock': The lock does not look stale, elapsed: 356 ms, giving up.
2024-11-12 12:15:06.032 [info] Lock '/user/gent/448/vsc44804/.local/share/code-server/User/workspaceStorage/-6392ac68-2/vscode.lock': Lock acquired.
2024-11-12 12:15:06.391 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-12 12:15:06.392 [info] ExtensionService#_doActivateExtension nextflow.nextflow, startup: false, activationEvent: 'onLanguage:nextflow-config'
2024-11-12 12:15:06.504 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-12 12:15:06.543 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-12 12:15:06.543 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-12 12:15:06.782 [info] Eager extensions activated
2024-11-12 12:15:06.782 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-12 12:15:06.782 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-12 12:15:07.618 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-11-12 12:15:07.656 [error] Error: Pending response rejected since connection got disposed
	at Object.dispose (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:17797:27)
	at Object.dispose (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3880:35)
	at LanguageClient.handleConnectionClosed (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3471:34)
	at LanguageClient.handleConnectionClosed (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:12410:22)
	at closeHandler (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3458:18)
	at CallbackList.invoke (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:17935:39)
	at Emitter.fire (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:17997:36)
	at closeHandler (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:16944:26)
	at CallbackList.invoke (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:17935:39)
	at Emitter.fire (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:17997:36)
	at StreamMessageWriter.fireClose (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:18882:27)
	at Socket.<anonymous> (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:18914:42)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)
2024-11-12 12:15:07.657 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3280:19)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3251:21)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:12380:22)
	at LanguageClient.doInitialize (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3233:27)
	at async LanguageClient.start (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3088:13)
2024-11-12 12:15:07.764 [error] Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3280:19)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3251:21)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:12380:22)
	at LanguageClient.doInitialize (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3233:27)
	at async LanguageClient.start (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3088:13)
2024-11-12 12:15:07.887 [error] Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3280:19)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3251:21)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:12380:22)
	at LanguageClient.doInitialize (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3233:27)
	at async LanguageClient.start (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3088:13)
2024-11-12 12:15:07.996 [error] Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3280:19)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3251:21)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:12380:22)
	at LanguageClient.doInitialize (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3233:27)
	at async LanguageClient.start (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3088:13)
2024-11-12 12:15:08.107 [error] Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3280:19)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3251:21)
	at LanguageClient.stop (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:12380:22)
	at LanguageClient.doInitialize (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3233:27)
	at async LanguageClient.start (/kyukon/home/gent/448/vsc44804/.local/share/code-server/extensions/nextflow.nextflow-1.0.0-universal/extension.js:3088:13)
2024-11-12 12:15:08.926 [debug] ProxyResolver#loadSystemCertificates count 150
2024-11-12 12:15:08.927 [debug] ProxyResolver#loadSystemCertificates parse error Error: error:0480006C:PEM routines::no start line
	at new X509Certificate (node:internal/crypto/x509:119:21)
	at /kyukon/home/apps/RHEL8/cascadelake-ib/software/code-server/4.93.1/lib/vscode/node_modules/@vscode/proxy-agent/out/index.js:518:48
	at Array.filter (<anonymous>)
	at /kyukon/home/apps/RHEL8/cascadelake-ib/software/code-server/4.93.1/lib/vscode/node_modules/@vscode/proxy-agent/out/index.js:516:26
	at Generator.next (<anonymous>)
	at fulfilled (/kyukon/home/apps/RHEL8/cascadelake-ib/software/code-server/4.93.1/lib/vscode/node_modules/@vscode/proxy-agent/out/index.js:32:58)
2024-11-12 12:15:08.957 [debug] ProxyResolver#loadSystemCertificates count filtered 149
2024-11-12 12:15:08.958 [debug] ProxyResolver#resolveProxy unconfigured https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-11-12 12:15:09.214 [debug] ProxyResolver#resolveProxy unconfigured https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
```

</details>

**Comment by nick-youngblut** [comment]
Thanks @ameintjes 

A caveat of the extension is that it assumes Nextflow is installed in the [user's base environment](https://www.nextflow.io/docs/latest/install.html#installation). Many users want to separate software into isolated environments. I've always installed Nextflow via conda, and so AFAIK the extension will not utilize java & nextflow installed in a conda env (I don't see anything in the settings). 

More generally, it would help if the [README](https://github.com/nextflow-io/vscode-language-nextflow) and the blog post on the [extension updates](https://seqera.io/blog/modernizing-nextflow-developer-experience/) pointed out that Java v17 or higher are required, especially given that some users have Nextflow installed via conda, so the extension just "won't work" in that situation.

**Comment by nick-youngblut** [comment]
I've installed java and nextflow in my base (os-level) environment:

```console
openjdk 23.0.1 2024-10-15
OpenJDK Runtime Environment Homebrew (build 23.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 23.0.1, mixed mode, sharing)
```

```console
nextflow -version 

      N E X T F L O W
      version 24.10.0 build 5928
      created 27-10-2024 18:36 UTC (11:36 PDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```

...and I'm still getting the same error:

![Screenshot 2024-11-12 at 8 31 52 AM](https://github.com/user-attachments/assets/90042129-59cb-4e5b-8a71-cb6fc19ce836)

Re-installing the extension and/or reloading the VS Code window does not help.

**Comment by bentsherman** [comment]
Try setting the "Nextflow > Java > Home" extension setting to an explicit Java path (should be the path containing the `bin` directory)

I'm beginning to suspect that Java installed via homebrew is not being auto-detected for some reason

**Comment by nvnieuwk** [comment]
That's what fixed the issue for us yesterday! Thank you!

**Comment by bentsherman** [comment]
@nvnieuwk are you using the homebrew install of Java?

**Comment by nvnieuwk** [comment]
Our issue was mainly that we were running it on a remote SSH connection with our HPC. The default Java version there is Java 8 which was too low. 

I don't know in what way Java was installed on the HPC tho

**Comment by bentsherman** [comment]
I haven't investigated the SSH setup too much but I'm glad you got it working. My understanding is that you would install the Nextflow extension through your local VS Code editor but install it to "SSH Remote" instead of "Local", is that right?

**Comment by nvnieuwk** [comment]
> I haven't investigated the SSH setup too much but I'm glad you got it working. My understanding is that you would install the Nextflow extension through your local VS Code editor but install it to "SSH Remote" instead of "Local", is that right?

Yes that's what we did. It was actually a browser code editor but that should work basically the same as a remote SSH

**Comment by bentsherman** [comment]
@nick-youngblut did you ever get it to work? Customizing "Nextflow > Java > Home" seems to fix the issue for others that had the same problem

**Comment by nick-youngblut** [comment]
Yeah, it was due to using java installed via conda. Once I realized that, it was straight forward to fix

**Comment by bentsherman** [comment]
Thanks for the update. I'll add a note to the docs about custom Java installs

**Comment by nick-youngblut** [comment]
The docs currently state:

```
Requirements
The language server requires Java 17 or later.
``

Here, it could be helpful to point out the docs about custom Java installs.
